[[redirects]]
  from = "/api/*"
  to = "https://personal-portfolio-maciej.herokuapp.com/:splat"
  status = 200
  force = true

[[headers]]
  for = "*"
  [headers.values]
  Access-Control-Allow-Origin = "*"